CREATE TABLE PORTFOLIOS(
ID VARCHAR(255) PRIMARY KEY);

CREATE TABLE SYMBOLS(
PORTFOLIO VARCHAR(255) NOT NULL,
SYMBOL VARCHAR(255) NOT NULL,
VOLUME NUMBER
);

ALTER TABLE SYMBOLS ADD PRIMARY KEY(PORTFOLIO,SYMBOL);